# Generated by Django 5.2.8 on 2025-12-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
